# Generated by Django 4.0.4 on 2022-05-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customercart_delete_usercart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercart',
            name='BookId',
        ),
        migrations.AddField(
            model_name='customercart',
            name='Bookid',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customercart',
            name='dummybooks',
            field=models.CharField(blank=True, default=['Python', 'CPP', 'JAVA', 'Django'], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customercart',
            name='Userid',
            field=models.IntegerField(),
        ),
    ]
