# Generated by Django 4.0.4 on 2022-05-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customercart_bookid_customercart_bookid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userid', models.IntegerField()),
                ('Bookid', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('dummybooks', models.CharField(blank=True, default=['Python', 'CPP', 'JAVA', 'Django'], max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='customerCart',
        ),
    ]
