# Generated by Django 4.0.4 on 2022-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_usercart_bookid_remove_usercart_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('bookID', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('dummybooks', models.CharField(blank=True, default=['Python', 'CPP', 'JAVA', 'Django'], max_length=200, null=True)),
            ],
        ),
    ]
