# Generated by Django 4.0.4 on 2022-05-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customercart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
