# Generated by Django 4.0.4 on 2022-05-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_usermain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollower',
            name='followerID',
            field=models.IntegerField(),
        ),
    ]
